-- ========================================================
-- KURA & ÖĞRENCİ PERFORMANS SİSTEMİ
-- Supabase (PostgreSQL) Veritabanı Şeması — Musa DİVARCI
-- ========================================================

-- 1. Tabloların Oluşturulması
CREATE TABLE IF NOT EXISTS classes (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id TEXT NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    in_pool SMALLINT NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ders_ici_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    class_id TEXT NOT NULL,
    type TEXT NOT NULL,
    delta INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS odev_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    class_id TEXT NOT NULL,
    type TEXT NOT NULL,
    delta INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS test_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    class_id TEXT NOT NULL,
    points INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS draw_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    class_id TEXT NOT NULL,
    student_name TEXT NOT NULL,
    drawn_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Row Level Security (RLS) Ayarları
-- Backend API üzerinden anon key veya service key ile güvenli erişim için
ALTER TABLE classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE ders_ici_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE odev_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE test_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE draw_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow full access to classes" ON classes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow full access to students" ON students FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow full access to ders_ici_logs" ON ders_ici_logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow full access to odev_logs" ON odev_logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow full access to test_logs" ON test_logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow full access to draw_history" ON draw_history FOR ALL USING (true) WITH CHECK (true);

-- 3. Varsayılan Sınıfları Ekle
INSERT INTO classes (id, name) VALUES 
('6', '6. Sınıf'),
('7', '7. Sınıf'),
('8', '8. Sınıf')
ON CONFLICT (id) DO NOTHING;

-- 4. 6. Sınıf Öğrencileri
INSERT INTO students (class_id, name, in_pool, sort_order) VALUES
('6', 'ATINÇ RÜZGAR KONUKMAN', 1, 0),
('6', 'AYAZ BİLGİN', 1, 1),
('6', 'AYAZ EMİR SELÇUK', 1, 2),
('6', 'ASYA ÇAKAR', 1, 3),
('6', 'BERAY KESKİN', 1, 4),
('6', 'BEREN UÇAR', 1, 5),
('6', 'BULUT KURT', 1, 6),
('6', 'CEYLİN ÜLKEBAY', 1, 7),
('6', 'ÇINAR YAVER', 1, 8),
('6', 'DENİZ GÜLER', 1, 9),
('6', 'ALİSA ÜŞÜDÜR', 1, 10),
('6', 'DEREN ÇOLAK', 1, 11),
('6', 'DERİN BERRAK ERKOÇ', 1, 12),
('6', 'DERİN DEMİR', 1, 13),
('6', 'DOĞA İPEKLİ', 1, 14),
('6', 'DURU AYVAZ', 1, 15),
('6', 'EGE POYRAZ ÇELİK', 1, 16),
('6', 'EMİR TOPAKKAYA', 1, 17),
('6', 'ÖYKÜ CEYLİN ÇİRKİN', 1, 18),
('6', 'HAZEL MİRA ÇİÇEK', 1, 19),
('6', 'MUSTAFA ÇINAR EROL', 1, 20),
('6', 'DERİN NAZ KARA', 1, 21),
('6', 'ÖYKÜ TUTKAÇ', 1, 22),
('6', 'İSMAİL BÜYÜKGENÇ', 1, 23),
('6', 'ECEM HİLAL', 1, 24),
('6', 'SEDANUR ÖZSOY', 1, 25),
('6', 'TANER TURNA', 1, 26),
('6', 'UMUT EFE KARAAĞAÇ', 1, 27),
('6', 'YİĞİT KARTAL', 1, 28),
('6', 'ZEYNEP İPEK BEKTAŞ', 1, 29),
('6', 'HALİL TİMUR YILDIRIM', 1, 30),
('6', 'MERAL KARTAL', 1, 31);

-- 5. 7. Sınıf Öğrencileri
INSERT INTO students (class_id, name, in_pool, sort_order) VALUES
('7', 'ALİ BERKER KESKİN', 1, 0),
('7', 'ALİ GALİP CAN ARICILAR', 1, 1),
('7', 'AYAZ ÖZDEK', 1, 2),
('7', 'YİĞİT TOPAL', 1, 3),
('7', 'AYTUĞ AKBULUT', 1, 4),
('7', 'BEYZA NEHİR ÇAN', 1, 5),
('7', 'TUANA ÇINAR', 1, 6),
('7', 'DURU YAŞAYANCAN', 1, 7),
('7', 'TUNA COMERT', 1, 8),
('7', 'EYLÜL KILIÇARSLAN', 1, 9),
('7', 'EGE UZUNHANÇERLİ', 1, 10),
('7', 'GÖKAY KIZILVERAN', 1, 11),
('7', 'GÖKHAN ERDEM', 1, 12),
('7', 'GÖKSU PEHLİVAN', 1, 13),
('7', 'DERİN SUNGUR', 1, 14),
('7', 'HATİCE TOPRAK ÖZER', 1, 15),
('7', 'ENES BAL', 1, 16),
('7', 'KARDELEN ÇAĞLAR', 1, 17),
('7', 'KAYRA SERKEK', 1, 18),
('7', 'MEDİNE ECE AĞLAR', 1, 19),
('7', 'MELİKE ŞEYMA BAY', 1, 20),
('7', 'EREN BALCI', 1, 21),
('7', 'MENEKŞE ADA AYAZ', 1, 22),
('7', 'YAĞMUR BARIN', 1, 23),
('7', 'NİLDA ÇİFÇİ', 1, 24),
('7', 'SUDENAZ UYSAL', 1, 25),
('7', 'TOPRAK ANIL KOLAÇ', 1, 26),
('7', 'TOPRAK BOZTEPE', 1, 27);

-- 6. 8. Sınıf Öğrencileri
INSERT INTO students (class_id, name, in_pool, sort_order) VALUES
('8', 'MURAT İNCE', 1, 0),
('8', 'ASYA NAZ KARAGÖZ', 1, 1),
('8', 'EYLÜL KAZANCI', 1, 2),
('8', 'EYLÜL YALÇINKAYA', 1, 3),
('8', 'EYNUR BERRU PEHLİVAN', 1, 4),
('8', 'GÜNEŞ DEMİRÖRS', 1, 5),
('8', 'ARMİN DALGIÇ', 1, 6),
('8', 'ŞEBNEM BURÇE ÇILDIR', 1, 7),
('8', 'ÇAĞAN MERT ŞAHİNBAŞ', 1, 8),
('8', 'ÇAĞAN TOPRAK KIZILIRMAK', 1, 9),
('8', 'ÇINAR COMERT', 1, 10),
('8', 'AYHAN YAĞIZ YILDIRIM', 1, 11),
('8', 'ÇINAR TERCANLI', 1, 12),
('8', 'DEMİR ÇAĞAN BELLEK', 1, 13),
('8', 'DERİN UMAY POLAT', 1, 14),
('8', 'GÜNEŞ SU ERAY', 1, 15),
('8', 'İLKİM NAZ AŞKIN', 1, 16),
('8', 'KAĞAN DİKENLİ', 1, 17),
('8', 'KEREM TÜRKOĞLU', 1, 18),
('8', 'MUHAMMET ALİ ERGÜN', 1, 19),
('8', 'MUSTAFA YİĞİT AKÇAKAYA', 1, 20),
('8', 'ALİ GAZİ ÖZDEMİR', 1, 21),
('8', 'ÖYKÜ ÖZCAN', 1, 22),
('8', 'MASAL İPEK', 1, 23),
('8', 'RÜZGAR YİĞİT', 1, 24),
('8', 'YAĞMUR YİĞİT', 1, 25),
('8', 'YİĞİT TERCANLI', 1, 26),
('8', 'ELA DENİZ ÇALIŞIR', 1, 27),
('8', 'CAN GÖKGÖZ', 1, 28);
